### PR TITLE
Fixed to allow simple text-only regexs to not have a comment

### LINKED ISSUE #68: regular-expression-comment: allow simple text-only regexs to not have a comment
Any regex without any special matching characters, e.g. `/some text/u` should not require a comment.

### PR DESCRIPTION
**Pull request by jpolavar**
Closes #68

### CODE REVIEW

**Comment by jpolavar** [comment]
tested on monitor service

File: src/regular-expression-comment.ts [hunk 1]
```diff
@@ -25,35 +25,41 @@ export default {
...
-            const regularExpression = /[a-zA-Z]/gu;
-            // This regex is to check if the line starts with or without spaces and followed by two or more consecutive slashes // or start with /* and may have one or more asterisks, continuing until the first occurrence of */.
-            const commentRegularExpressionLine = /^\s*(?:\/{2,}|\/\*+)/gu;
-            const hasComment = regularExpression.test(comment.value.trim());
-            if (comment.type === 'Line' || comment.loc.start.line === comment.loc.end.line) {
+
+          // Check if the regular expression contains any simple text
+          const isSimpleTextPattern = /^[0-9:./,\sa-zA-Z-]*$/gu.test(node.value.source);
+
+          if (!isSimpleTextPattern) {
```
Comment (carlansley) [inline src/regular-expression-comment.ts:32]: i think it would be better to do a `if (isSimpleTextPattern)` and just return.  makes the diff easier to follow too.

**Review by carlansley — CHANGES_REQUESTED** [review]

**Review by carlansley — APPROVED** [review]
