### PR TITLE
Fixed issue to report empty comments issue for regex

### LINKED ISSUE #51: Fix to report any empty comment around regex
const skimmedFromDate = from.replaceAll(/\W/gu, ''); // test
    const skimmedToDate = to.replaceAll(/\W/gu, '');
the second line in this should be an error, but it's not. probably because there is a comment in the line prior

### PR DESCRIPTION
**Pull request by jpolavar**
Closes #51

### CODE REVIEW

File: src/regular-expression-comment.ts [hunk 1]
```diff
@@ -24,10 +24,28 @@ export default {
           const regexLine = node.loc?.start.line;
           if (regexLine) {
             const previousLine = regexLine - 1;
-
-            const hasRegexComment = comments.find(
-              (comment) => comment.loc?.start.line === previousLine || comment.loc?.start.line === regexLine,
-            );
+            const hasRegexComment = comments.find((comment) => {
```
Comment (carlansley) [inline src/regular-expression-comment.ts:27]: inconsistent camel-casing of Regex/regExp etc.  I recommend eliminating the abbreviation and just going with e.g. regularExpression

File: src/regular-expression-comment.ts [hunk 2]
```diff
@@ -24,10 +24,28 @@ export default {
...
+              if (!comment.loc) {
+                return false;
+              }
+              const regExp = /[a-zA-Z]/gu;
+              const commentRegExp = /^(?:\/{2,}|\/\*+)/gu;
+              const hasComment = regExp.test(comment.value.trim());
+              const previousLineComment = context.sourceCode.getLines()[previousLine - 1];
```
Comment (carlansley) [inline src/regular-expression-comment.ts:34]: this looks potentially hazardous performance wise, calling `context.sourceCode.getLines()` for every regular expression.  Since its not going to change, I'd get that value up at the top where you also get the comments.

File: src/regular-expression-comment.ts [hunk 3]
```diff
@@ -24,10 +24,28 @@ export default {
           const regexLine = node.loc?.start.line;
           if (regexLine) {
```
Comment (carlansley) [inline src/regular-expression-comment.ts:25]: this would fail the new truthiness check we do as part of our normal config, could you add that to the rules for this repo and fix?

**Review by carlansley — CHANGES_REQUESTED** [review]

**Comment by carlansley** [comment]
adding @ramaghanta since he's more familiar with the bug

**Review by ramaghanta — APPROVED** [review]
lgtm

File: src/regular-expression-comment.ts [hunk 4]
```diff
@@ -20,21 +20,37 @@ export default {
...
-          const regexLine = node.loc?.start.line;
-          if (regexLine) {
-            const previousLine = regexLine - 1;
-
-            const hasRegexComment = comments.find(
-              (comment) => comment.loc?.start.line === previousLine || comment.loc?.start.line === regexLine,
+        if (node.loc && node.value instanceof RegExp) {
+          const regularExpressionLine = node.loc.start.line;
+          const previousLine = regularExpressionLine - 1;
+          const previousLineComment = context.sourceCode.getLines()[previousLine - 1];
```
Comment (carlansley) [inline src/regular-expression-comment.ts:26]: the `context.sourceCode.getLines()` hasn't been moved to the top yet

**Review by carlansley — CHANGES_REQUESTED** [review]

**Review by carlansley — APPROVED** [review]
